// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.12.4
// source: media/mediapb/media.proto

// command to generate
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./media/mediapb/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentRequest) Reset() {
	*x = SegmentRequest{}
	mi := &file_media_mediapb_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRequest) ProtoMessage() {}

func (x *SegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_mediapb_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRequest.ProtoReflect.Descriptor instead.
func (*SegmentRequest) Descriptor() ([]byte, []int) {
	return file_media_mediapb_media_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BodyChunk     []byte                 `protobuf:"bytes,1,opt,name=bodyChunk,proto3" json:"bodyChunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentResponse) Reset() {
	*x = SegmentResponse{}
	mi := &file_media_mediapb_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentResponse) ProtoMessage() {}

func (x *SegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_mediapb_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentResponse.ProtoReflect.Descriptor instead.
func (*SegmentResponse) Descriptor() ([]byte, []int) {
	return file_media_mediapb_media_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentResponse) GetBodyChunk() []byte {
	if x != nil {
		return x.BodyChunk
	}
	return nil
}

var File_media_mediapb_media_proto protoreflect.FileDescriptor

var file_media_mediapb_media_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x62, 0x2f,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x70, 0x62, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2f, 0x0a, 0x0f, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x6f, 0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x53, 0x0a, 0x0c, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x64, 0x69, 0x74, 0x2d, 0x62, 0x69, 0x74, 0x2f, 0x73, 0x6f, 0x6e, 0x65, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_media_mediapb_media_proto_rawDescOnce sync.Once
	file_media_mediapb_media_proto_rawDescData = file_media_mediapb_media_proto_rawDesc
)

func file_media_mediapb_media_proto_rawDescGZIP() []byte {
	file_media_mediapb_media_proto_rawDescOnce.Do(func() {
		file_media_mediapb_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_media_mediapb_media_proto_rawDescData)
	})
	return file_media_mediapb_media_proto_rawDescData
}

var file_media_mediapb_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_media_mediapb_media_proto_goTypes = []any{
	(*SegmentRequest)(nil),  // 0: mediapb.SegmentRequest
	(*SegmentResponse)(nil), // 1: mediapb.SegmentResponse
}
var file_media_mediapb_media_proto_depIdxs = []int32{
	0, // 0: mediapb.MediaService.GetSegment:input_type -> mediapb.SegmentRequest
	1, // 1: mediapb.MediaService.GetSegment:output_type -> mediapb.SegmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_mediapb_media_proto_init() }
func file_media_mediapb_media_proto_init() {
	if File_media_mediapb_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_media_mediapb_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_mediapb_media_proto_goTypes,
		DependencyIndexes: file_media_mediapb_media_proto_depIdxs,
		MessageInfos:      file_media_mediapb_media_proto_msgTypes,
	}.Build()
	File_media_mediapb_media_proto = out.File
	file_media_mediapb_media_proto_rawDesc = nil
	file_media_mediapb_media_proto_goTypes = nil
	file_media_mediapb_media_proto_depIdxs = nil
}
