// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: users/gluserpb/user.proto

package gluserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoogleUserServiceClient is the client API for GoogleUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoogleUserServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type googleUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoogleUserServiceClient(cc grpc.ClientConnInterface) GoogleUserServiceClient {
	return &googleUserServiceClient{cc}
}

func (c *googleUserServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/gluserpb.GoogleUserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleUserServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/gluserpb.GoogleUserService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoogleUserServiceServer is the server API for GoogleUserService service.
// All implementations must embed UnimplementedGoogleUserServiceServer
// for forward compatibility
type GoogleUserServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	mustEmbedUnimplementedGoogleUserServiceServer()
}

// UnimplementedGoogleUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoogleUserServiceServer struct {
}

func (UnimplementedGoogleUserServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGoogleUserServiceServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedGoogleUserServiceServer) mustEmbedUnimplementedGoogleUserServiceServer() {}

// UnsafeGoogleUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoogleUserServiceServer will
// result in compilation errors.
type UnsafeGoogleUserServiceServer interface {
	mustEmbedUnimplementedGoogleUserServiceServer()
}

func RegisterGoogleUserServiceServer(s grpc.ServiceRegistrar, srv GoogleUserServiceServer) {
	s.RegisterService(&GoogleUserService_ServiceDesc, srv)
}

func _GoogleUserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleUserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gluserpb.GoogleUserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleUserServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleUserService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleUserServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gluserpb.GoogleUserService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleUserServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoogleUserService_ServiceDesc is the grpc.ServiceDesc for GoogleUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoogleUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gluserpb.GoogleUserService",
	HandlerType: (*GoogleUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GoogleUserService_Get_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _GoogleUserService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/gluserpb/user.proto",
}
